// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwcesdsthsblikjjusmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3Y2VzZHN0aHNibGlramp1c21jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNTAzNTQsImV4cCI6MjA3MDcyNjM1NH0.bPHbI1DsAIx2V99hpNi4KUeAi3mO1HHi-ux1_6Ha_Rw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});